name: ubi
on:
  #schedule:
  #  - cron: '31 14 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  MAJOR: 9
  MINOR: 1

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #     # This is used to complete the identity challenge
  #     # with sigstore/fulcio when running outside of PRs.
  #     id-token: write

    # steps:

    #   # - name: Checkout repository
    #   #   uses: actions/checkout@v3

    #   - name: Adding markdown1
    #     run: echo '# Hello world! 🚀' >> $GITHUB_STEP_SUMMARY

    #   - name: Adding markdown2
    #     run: echo '# Hello world2! 🚀\n' >> $GITHUB_STEP_SUMMARY
  GenerateImageReleaseReport:
    name: Generate image release report
    if: ${{ always() }}
    # needs: [ Initialize, ReleaseImages ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      - name: Generate images release report
        run: |
          echo '# Hello world! 🚀' >> $GITHUB_STEP_SUMMARY

  GeneratePackagesReleaseReport:
    name: Generate packages release report
    if: ${{ always() }}
    # needs: [ Initialize, ReleasePackages ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      - name: Generate pakages release report
        run: |
          echo '# Hello world! 🚀' >> $GITHUB_STEP_SUMMARY

