name: Image Build

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version (optional)'
        required: false

env:
  REGISTRY: ghcr.io
  MAJOR: 11
  MINOR: 0
  FIX: 1

jobs:
  initialize:
    runs-on: ubuntu-latest
    name: Initialize
    outputs:
      images: ${{ steps.identify-images.outputs.images }}
      images_metadata: ${{ steps.identify-images.outputs.images_metadata }}
      version: ${{ steps.identify-images.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Identify images
        id: identify-images
        run: |
            ./scripts/initialize.sh ${{ github.ref }} ${{ github.ref_type }} ${{ github.event.inputs.version }}

  BuildImages:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [initialize]
    outputs:
      images_metadata: ${{ steps.set_metadata.outputs.images_metadata }}
    strategy:
      matrix:
        image: ${{ fromJson(needs.initialize.outputs.images) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract image version
        id: extract_version
        run: |
          VERSION=$(./scripts/get_image_version.sh "${{ needs.initialize.outputs.images_metadata }}" "${{ matrix.image }}")
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{github.repository_owner}}/${{ matrix.image }}
          flavor: latest=true
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.extract_version.outputs.VERSION }}.${{ github.run_number }}
          labels: |
            maintainer=${{github.repository_owner}}
            name=${{github.repository_owner}}/${{ matrix.image }}
            io.k8s.display-name=${{github.repository_owner}}/${{ matrix.image }}
            version=${{ steps.extract_version.outputs.VERSION }}
            org.opencontainers.image.title=${{github.repository_owner}}/${{ matrix.image }}
            org.opencontainers.image.version=${{ steps.extract_version.outputs.VERSION }}.${{ github.run_number }}
            org.opencontainers.image.description=${{github.repository_owner}}/${{ matrix.image }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:builders"
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.image }}/${{ matrix.image }}.Dockerfile
          platforms: linux/amd64,linux/arm64
      - name: Set image metadata
        id: set_metadata
        run: |
          # Create an associative array to store metadata and image ID for each image
          result=""
          created=$(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.labels."org.opencontainers.image.created"')
          BUILD_TAG=$(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.labels."org.opencontainers.image.version"')
          imageid=$(echo ${{ steps.build-and-push.outputs.imageID }} | sed 's/^sha256://' | cut -c1-12)
          result="{ \"${{ matrix.image }}\": { \"BUILD_TAG\":\"${BUILD_TAG}\",\"IMAGE_ID\":\"$imageid\",\"CREATED\":\"${created}\" } }"

          echo "images_metadata=[$result]" >> $GITHUB_OUTPUT

  GenerateImageReleaseReport:
    name: Generate image release - ${{ needs.initialize.outputs.version }}
    if: ${{ success() }}
    needs: [initialize, BuildImages]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate images release report
        id: generate_release
        run: |
          images=($(echo '${{ needs.initialize.outputs.images }}' | jq -r '.[]'))
          JSON_DATA='${{ needs.BuildImages.outputs.images_metadata }}'
          releaseReport="# 🚀 Released Packages $RELEASE 🚀\n"
          releaseReport+="| 📦 Package | Image Tag | SHA | Created Date |\n"
          releaseReport+="| :-: | :-: | :-: | :-: |"
          echo "DEBUG: Metadata : $JSON_DATA"

          for image in "${images[@]}"; do
            BUILD_TAG=$(echo "$JSON_DATA" | jq -r ".[] | .$image.BUILD_TAG")
            IMAGE_ID=$(echo "$JSON_DATA" | jq -r ".[] | .$image.IMAGE_ID")
            CREATED=$(echo "$JSON_DATA" | jq -r ".[] | .$image.CREATED")
            # Include the metadata in the release report
            releaseReport+="\n|$image|${BUILD_TAG}|${IMAGE_ID}|${CREATED}|"
          done
          echo -e "$releaseReport" >> $GITHUB_STEP_SUMMARY
          echo -e "\n" >> $GITHUB_STEP_SUMMARY

          RELEASE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ needs.initialize.outputs.version }}" | jq -r '.id')
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV

          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d '{"body": "'"$releaseReport"'"}' "https://api.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}"
