name: Image Build
on:
  #schedule:
  #  - cron: '31 14 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  MAJOR: 11
  MINOR: 0
  FIX: 1

jobs:
  initialize:
    # The workflow runs on self hosted runner, having docker available
    runs-on: [ ubuntu-latest ]
    name: Initialize
    outputs:
      images: ${{ steps.identify-images.outputs.images }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Identify images
        id: identify-images
        run: |
              cd builders
              result=""
              for d in * ; do
                #if [ -f "$d/build.sh" ]; then
                  if [ -z $result ]; then
                    result="$d"
                  else
                    result="$result,$d"
                  fi
                #fi
              done
              #echo $result
              echo "images=$result" >> $GITHUB_OUTPUT
              #echo "{images}={result}" >> $GITHUB_OUTPUT
      - name: Get Version
        id: get_version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export VERSION="${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.FIX }}"
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            # Extract version from the tag and remove the 'v' prefix
            export VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
          else
            export VERSION=${{ github.sha }}
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      # - name: Prepare Git credentials script
      #   run: echo 'echo ${GITHUB_TOKEN}' > $GIT_ASKPASS && chmod +x $GIT_ASKPASS

  GenerateImageReleaseReport:
    name: Generate image release report
    if: ${{ always() }}
    needs: [ initialize ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      - name: Generate images release report
        run: |
          images=${{ needs.initialize.outputs.images }}
          releaseReport="# 🚀 Released Packages $RELEASE 🚀\n"
          releaseReport+="| 📦 Package | Internal Repository Location | Public Repository Location |\n"
          releaseReport+="| :-: | :-: | :-: |"
          IFS=',' read -ra imageArray <<< "$images"
          for image in "${imageArray[@]}"; do
            releaseReport+="\n|$image|${{ needs.initialize.outputs.version }}|1.0.0|"
          done
          echo -e "$releaseReport" >> $GITHUB_STEP_SUMMARY
          echo -e "\n" >> $GITHUB_STEP_SUMMARY

  # GeneratePackagesReleaseReport:
  #   name: Generate packages release report
  #   if: ${{ always() }}
  #   # needs: [ Initialize, ReleasePackages ]
  #   runs-on: [ ubuntu-latest ]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

  #     - name: Generate pakages release report
  #       run: |
  #         echo '# Hello world! 🚀' >> $GITHUB_STEP_SUMMARY

