name: Image Build

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version (optional)'
        required: false

env:
  REGISTRY: ghcr.io
  MAJOR: 11
  MINOR: 0
  FIX: 1

jobs:
  initialize:
    runs-on: ubuntu-latest
    name: Initialize
    outputs:
      images: ${{ steps.identify-images.outputs.images }}
      images_metadata: ${{ steps.identify-images.outputs.images_metadata }}
      version: ${{ steps.identify-images.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Identify images
        id: identify-images
        run: |
          cd builders
          result=""
          result1=""
          ########## VERSION
            if [ -n "${{ github.event.inputs.version }}" ]; then
              export VERSION=${{ github.event.inputs.version }}
            elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              export VERSION="${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.FIX }}"
            elif [[ "${{ github.ref_type }}" == "tag" ]]; then
              export VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
            else
              export VERSION=${{ github.ref_name }}
            fi
          #########
          for d in * ; do
            if [ -d "$d" ] && [ ! -f "$d/skip" ]; then
              if [ -z "$result" ]; then
                result="\"$d\""
                result1="{ \"$d\": { \"version\": \"$VERSION\" } }"
              else
                result+=",\"$d\""
                result1+=", \"$d\": { \"version\": \"$VERSION\" }"
              fi
            fi
          done
          echo "images=[$result]" >> $GITHUB_OUTPUT
          echo "images_metadata=[$result1]" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  BuildImages:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [initialize]
    outputs:
      images_metadata: ${{ steps.set_metadata.outputs.images_metadata }}
    strategy:
      matrix:
        image: ${{ fromJson(needs.initialize.outputs.images) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{github.repository_owner}}/${{ matrix.image }}
          flavor: latest=true
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ needs.initialize.outputs.version }}.${{ github.run_number }}
          labels: |
            maintainer=${{github.repository_owner}}
            name=${{github.repository_owner}}/${{ matrix.image }}
            io.k8s.display-name=${{github.repository_owner}}/${{ matrix.image }}
            version=${{ needs.initialize.outputs.version }}
            org.opencontainers.image.title=${{github.repository_owner}}/${{ matrix.image }}
            org.opencontainers.image.version=${{ needs.initialize.outputs.version }}.${{ github.run_number }}
            org.opencontainers.image.description=${{github.repository_owner}}/${{ matrix.image }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:builders"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.image }}/${{ matrix.image }}.Dockerfile
          platforms: linux/amd64,linux/arm64
      - name: Set image metadata
        id: set_metadata
        run: |
          # Create an associative array to store metadata and image ID for each image
          result=""
          created=$(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.labels."org.opencontainers.image.created"')
          BUILD_TAG=$(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.labels."org.opencontainers.image.version"')
          imageid=$(echo ${{ steps.build-and-push.outputs.imageID }} | cut -c1-12)
          result="{ \"${{ matrix.image }}\": { \"BUILD_TAG\":\"${BUILD_TAG}\",\"IMAGE_ID\":\"$imageid\",\"CREATED\":\"${created}\",\"METADATA\":\"$DOCKER_METADATA_OUTPUT_JSON\" } }"

          echo "images_metadata=[$result]" >> $GITHUB_OUTPUT

  GenerateImageReleaseReport:
    name: Generate image release - ${{ needs.initialize.outputs.version }}
    if: ${{ success() }}
    needs: [initialize, BuildImages]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate images release report
        id: generate_release
        run: |
          images=($(echo '${{ needs.initialize.outputs.images }}' | jq -r '.[]'))
          releaseReport="# 🚀 Released Packages $RELEASE 🚀\n"
          releaseReport+="| 📦 Package | Image Tag | SHA | Created Date | Image Size |\n"
          releaseReport+="| :-: | :-: | :-: | :-: | :-: |"
          echo "DEBUG: Metadata for $image: ${{ needs.BuildImages.outputs.images_metadata }}"

          for image in "${images[@]}"; do

            metadata_key="METADATA_${image}"
            metadata=${!metadata_key}

            # Extract required metadata fields
            created=$(echo "$metadata" | jq -r '.labels."org.opencontainers.image.created"')
            BUILD_TAG=$(echo "$metadata" | jq -r '.labels."org.opencontainers.image.version"')
            imageid_key="IMAGEID_${image}"
            imageid=${!imageid_key}
            IMAGE_ID=${!metadata_key}
            echo "DEBUG: Image: $image, BUILD_TAG: $BUILD_TAG, created: $created, Image ID: $imageid"
            echo "$metadata"
            # Include the metadata in the release report
            releaseReport+="\n|$image|${BUILD_TAG}|${IMAGE_ID}|${created}|${imageSize} bytes|"
          done

          echo -e "$releaseReport" >> $GITHUB_STEP_SUMMARY
          echo -e "\n" >> $GITHUB_STEP_SUMMARY

          RELEASE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ needs.initialize.outputs.version }}" | jq -r '.id')
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV

          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d '{"body": "'"$releaseReport"'"}' "https://api.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}"
